### ISSUE TITLE
Strange behaviour with console under a certain size.

### ISSUE THREAD

**Issue by juan7732** [OneLoneCoder/Javidx9#2]
The Console Game Engine is great for quick prototyping, however, I noticed that in visual studio 2017, when I create a console whose title does not show the FPS counter, any operation to the console itself is sluggish and creates a ghost of a cursor until the operation is completed. This was reproduces many times with a console of size 50,50 and font 10,10. The solution I encountered was to increase the width of the console itself which alleviates the problem immediately.

**Comment by OneLoneCoder** [comment]
Interesting... I'll keep an eye out for this, thanks
