### ISSUE TITLE
Missing assets from multiple videos

### ISSUE THREAD

**Issue by Ike-Clinton** [OneLoneCoder/Javidx9#75]
I have noticed that several videos are missing assets for instance the 100k SHMUP video. The following files are nowhere to be found.

		sprPlayer = new olc::Sprite("gfx//100k_player.png");

		sprEnemy[0] = new olc::Sprite("gfx//100k_enemy1.png");

		sprEnemy[1] = new olc::Sprite("gfx//100k_enemy2.png");

		sprEnemy[2] = new olc::Sprite("gfx//100k_enemy3.png");

**Comment by OneLoneCoder** [comment]
The licence for those assets prohibits their distribution. I'm sure you can find suitable alternatives on many sprite resource sites.
